export const Cards = [
    {
        type: "Hearts",
        val: "Ace",
        point: 1,
        pointBis: 11,
        image: "hearts-ace",
    },
    {
        type: "Hearts",
        val: "2",
        point: 2,
        image: "hearts-two",
    },
    {
        type: "Hearts",
        val: "3",
        point: 3,
        image: "hearts-three",
    },
    {
        type: "Hearts",
        val: "4",
        point: 4,
        image: "hearts-four",
    },
    {
        type: "Hearts",
        val: "5",
        point: 5,
        image: "hearts-five",
    },
    {
        type: "Hearts",
        val: "6",
        point: 6,
        image: "hearts-six",
    },
    {
        type: "Hearts",
        val: "7",
        point: 7,
        image: "hearts-seven",
    },
    {
        type: "Hearts",
        val: "8",
        point: 8,
        image: "hearts-eight",
    },
    {
        type: "Hearts",
        val: "9",
        point: 9,
        image: "hearts-nine",
    },
    {
        type: "Hearts",
        val: "10",
        point: 10,
        image: "hearts-ten",
    },
    {
        type: "Hearts",
        val: "Jack",
        point: 10,
        image: "hearts-jack",
    },
    {
        type: "Hearts",
        val: "Queen",
        point: 10,
        image: "hearts-queen",
    },
    {
        type: "Hearts",
        val: "King",
        point: 10,
        image: "hearts-king",
    },
    {
        type: "Clubs",
        val: "Ace",
        point: 1,
        pointBis: 11,
        image: "clubs-ace",
    },
    {
        type: "Clubs",
        val: "2",
        point: 2,
        image: "clubs-two",
    },
    {
        type: "Clubs",
        val: "3",
        point: 3,
        image: "clubs-three",
    },
    {
        type: "Clubs",
        val: "4",
        point: 4,
        image: "clubs-four",
    },
    {
        type: "Clubs",
        val: "5",
        point: 5,
        image: "clubs-five",
    },
    {
        type: "Clubs",
        val: "6",
        point: 6,
        image: "clubs-six",
    },
    {
        type: "Clubs",
        val: "7",
        point: 7,
        image: "clubs-seven",
    },
    {
        type: "Clubs",
        val: "8",
        point: 8,
        image: "clubs-eight",
    },
    {
        type: "Clubs",
        val: "9",
        point: 9,
        image: "clubs-nine",
    },
    {
        type: "Clubs",
        val: "10",
        point: 10,
        image: "clubs-ten",
    },
    {
        type: "Clubs",
        val: "Jack",
        point: 10,
        image: "clubs-jack",
    },
    {
        type: "Clubs",
        val: "Queen",
        point: 10,
        image: "clubs-queen",
    },
    {
        type: "Clubs",
        val: "King",
        point: 10,
        image: "clubs-king",
    },
    {
        type: "Diamonds",
        val: "Ace",
        point: 1,
        pointBis: 11,
        image: "diamonds-ace",
    },
    {
        type: "Diamonds",
        val: "2",
        point: 2,
        image: "diamonds-two",
    },
    {
        type: "Diamonds",
        val: "3",
        point: 3,
        image: "diamonds-three",
    },
    {
        type: "Diamonds",
        val: "4",
        point: 4,
        image: "diamonds-four",
    },
    {
        type: "Diamonds",
        val: "5",
        point: 5,
        image: "diamonds-five",
    },
    {
        type: "Diamonds",
        val: "6",
        point: 6,
        image: "diamonds-six",
    },
    {
        type: "Diamonds",
        val: "7",
        point: 7,
        image: "diamonds-seven",
    },
    {
        type: "Diamonds",
        val: "8",
        point: 8,
        image: "diamonds-eight",
    },
    {
        type: "Diamonds",
        val: "9",
        point: 9,
        image: "diamonds-nine",
    },
    {
        type: "Diamonds",
        val: "10",
        point: 10,
        image: "diamonds-ten",
    },
    {
        type: "Diamonds",
        val: "Jack",
        point: 10,
        image: "diamonds-jack",
    },
    {
        type: "Diamonds",
        val: "Queen",
        point: 10,
        image: "diamonds-queen",
    },
    {
        type: "Diamonds",
        val: "King",
        point: 10,
        image: "diamonds-king",
    },
    {
        type: "Spades",
        val: "Ace",
        point: 1,
        pointBis: 11,
        image: "spades-ace",
    },
    {
        type: "Spades",
        val: "2",
        point: 2,
        image: "spades-two",
    },
    {
        type: "Spades",
        val: "3",
        point: 3,
        image: "spades-three",
    },
    {
        type: "Spades",
        val: "4",
        point: 4,
        image: "spades-four",
    },
    {
        type: "Spades",
        val: "5",
        point: 5,
        image: "spades-five",
    },
    {
        type: "Spades",
        val: "6",
        point: 6,
        image: "spades-six",
    },
    {
        type: "Spades",
        val: "7",
        point: 7,
        image: "spades-seven",
    },
    {
        type: "Spades",
        val: "8",
        point: 8,
        image: "spades-eight",
    },
    {
        type: "Spades",
        val: "9",
        point: 9,
        image: "spades-nine",
    },
    {
        type: "Spades",
        val: "10",
        point: 10,
        image: "spades-ten",
    },
    {
        type: "Spades",
        val: "Jack",
        point: 10,
        image: "spades-jack",
    },
    {
        type: "Spades",
        val: "Queen",
        point: 10,
        image: "spades-queen",
    },
    {
        type: "Spades",
        val: "King",
        point: 10,
        image: "spades-king",
    },
];